解决 cupertino复制粘贴弹窗报错的问题 NosuchMethodError: The getter 'pasterButtonLabel' was called on null. Receiver: null Tried calling: pasteButtonLabel 解决方法： https://juejin.im/entry/5cb459415188251aeb3ecb89